# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39dd96f4a134c64bcfe3ff7136b6c97575b258f9c2ade110727e237710d42276e6659563b4ab38f38a2f2efce92566b2cc22cf28123d586a24b62ac2a90f5c65

test:
  secret_key_base: 95f5ee87bd6027b0f49e99d7e17197217b3adf7a18123db87158944c736cf06a3832a9d255a2ffc3bb651c7502ec83157425e9f8ba50e92c32cd8b685e461fdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
